app/__init__.py
from flask import Flask
from flask_cors import CORS
from .config import config
from .exts import toolbar

from app.index import bp as index_bp
from app.kits import bp as kits_bp
from app.api.v_1_0 import bp as v_1_0_bp


def create_app(config_name):
    app = Flask(__name__)

    app.config.from_object(config[config_name])

    app.register_blueprint(index_bp)
    app.register_blueprint(kits_bp)
    app.register_blueprint(v_1_0_bp)

    if config_name=="development":
        toolbar.init_app(app)
    # CORS(app, resources=r'/api/*')

    return app

app/api/v_1_0/__init__.py
from flask import Blueprint
from flask_restful import Api, Resource

from app.libs.utils import import_all_modules

bp = Blueprint('api.v_1_0', __name__, url_prefix='/api/v1.0')

restful_api = Api(bp)

import_all_modules(__name__,include_packages=True, recursive=True)

app/api/v_1_0/main.py
"""
首页资源
"""
from flask_restful import Resource
from . import restful_api


class Index(Resource):

    def get(self):
        return {
            'status': 200,
            'msg': 'Get 来自蓝图restful'
        }

    def post(self):
        return {
            'status': 200,
            'msg': 'POST 来自蓝图restful'
        }

    def put(self):
        return {
            'status': 200,
            'msg': 'PUT 来自蓝图restful'
        }

    def delete(self):
        return {'msg': 'DELETE 来自蓝图restful'}


restful_api.add_resource(Index, '/index')

app/index/__init__.py
from flask import Blueprint

bp = Blueprint('index', __name__, url_prefix='')

from . import views

app/index/views.py
import os
import sys
from flask import render_template
from . import bp


@bp.route('/')
def index():
    system_info = [{
        'name':'操作系统',
        'val':sys.platform,
        'note':''
    },{
        'name':'系统编码',
        'val':sys.getfilesystemencoding(),
          'note':''
    }]

    data={
        'url_name':'index',
        'system_info':system_info
    }
    print(system_info)
    return render_template('index.html',data=data)

app/kits/__init__.py
from flask import Blueprint

bp = Blueprint('kits', __name__, url_prefix='/kits')

from . import views

app/kits/views.py
import os
import sys
from flask import render_template
from . import bp


@bp.route('/')
def kits():
    data={
        'url_name':'kits'
    }
    return render_template('kits.html',data=data)

app/templates/base.html
<!DOCTYPE html>
<html>
<meta charset="utf-8">
 {% block meta %}{% endblock %}
<link rel="stylesheet" type="text/css" href="../static/semantic/semantic.min.css"> {% block css %}{% endblock %}

<head>
    <title>{% block title %}WallE{% endblock %}</title>
</head>

<body>
<div class="ui container">
    <div class="ui three item menu">
      <a class="item  {% if  data.url_name == 'index' %}active{%else%}{%endif%}" href="{{url_for('index.index')}}">系统</a>
      <a class="item  {% if  data.url_name == 'kits' %}active{%else%}{%endif%}" href="{{url_for('kits.kits')}}">工具</a>
      <a class="item">其他</a>
    </div>
        {% block body %}{% endblock %}
</div>

    <script type="text/javascript" src="../static/js/lib/jquery.min.js"></script>
    <script type="text/javascript" src="../static/js/lib/axios.min.js"></script>
    <script type="text/javascript" src="../static/js/lib/vue.min.js"></script>
    <script type="text/javascript" src="../static/js/lib/vue-router.min.js"></script>
    <script type="text/javascript" src="../static/semantic/.min.js"></script>
    {% block js %}{% endblock %}
</body>

</html>

app/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="ui container">
    <table class="ui celled table">
      <thead>
        <tr>
          <th>系统属性</th>
          <th>值</th>
          <th>备注</th>
        </tr>
      </thead>
      <tbody>
      {% for info in data.system_info%}
        <tr >
          <td>{{info.name}}</td>
          <td>{{info.val}}</td>
          <td>{% if info.note%}{{info.note}} {%else%}{%endif%}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

app/templates/kits.html
{% extends "base.html" %}
{% block body %}
<div id="tools-cont" class="tools-cont ui grid">
  <div class="four wide column">
    <div class="ui vertical fluid tabular menu">
    <router-link class="item" to="/foo">切换Host</router-link>
    <router-link class="item" to="/bar">开发中</router-link>

    </div>
  </div>
  <div class="twelve wide stretched column">
    <div class="ui segment">
     <router-view></router-view>
    </div>
  </div>
</div>
{% endblock %}
{% block js%}
<script>
const Foo = { template: '<div>foo</div>' }
const Bar = { template: '<div>bar</div>' }

const routes = [
  { path: '/foo', component: Foo },
  { path: '/bar', component: Bar }
]

const router = new VueRouter({
  routes,
  linkActiveClass:'active'
})

const app = new Vue({
  router
}).$mount('#tools-cont')

</script>


{%endblock%}